language: c

compiler:
  - gcc

env:
  global:
  - CODECOV_TOKEN="13ac58ad-1484-4db4-a4e9-71545eaf5874"

install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo apt-get install cmake
  - sudo apt-get install lcov
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

os:
  - linux

before_script:
  - cd dz2
  - mkdir build
  - cd build
  - cmake ..

script:
  - make st_main.out
  - make dyn_main.out
  - sh ../diff_test.sh
  - cppcheck —inconclusive —enable=all —check-config —suppress=missingIncludeSystem -q -v --error-exitcode=1 ../
  - make st_test.out
  - ./st_test.out
  - make dyn_test.out
  - ./dyn_test.out

after_script:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info
  - make clean