language: c

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck

os:
  - linux

script:
  - make test.out
  - valgrind ./test.out
  - cppcheck —inconclusive —enable=all —check-config —suppress=missingIncludeSystem -q --std=c99

after_script:
  - make clean