language: c

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo apt-get install cmake

os:
  - linux

script:
  - cmake
  - make main.out
  - make test.out
  - valgrind ./main.out < in.txt
  - cppcheck —inconclusive —enable=all —check-config —suppress=missingIncludeSystem -q -v --error-exitcode=1 --std=c99
  - ./test.out

after_script:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  - make clean